name: called B

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
  
jobs:
  called-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo Hello, world 
